<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;

class OrderPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'pic_id'=>'required',
            'number'=>'required|unique:orders'
        ];
    }
    public function messages()
    {
        return [
            'pic_id.required'=>'参数不能为空！',
            'number.required'=>'参数不能为空！',
            'number.unique'=>'订单号不能重复！'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'message'=>$errors[0],
            'code'=>'ERROR'
        ], 422);
    }
}
