<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;

class PicturePost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'url'=>'required',
            'category'=>'required|integer',
            'money'=>'nullable|numeric',
        ];
    }
    public function messages()
    {
        return [
            'url.required'=>'URL不能为空！',
            'category.required'=>'分类不能为空！',
            'category.integer'=>'参数格式必须为整形！',
            'money.numeric'=>'参数格式不正确！'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'message'=>$errors[0]
        ], 422);
    }
}
