<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;

class TeacherPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'number'=>'required|unique:teachers|integer',
            'name'=>'required',
            'category'=>'required|integer',
        ];
    }
    public function messages()
    {
        return [
            'number.required'=>'编号不能为空！',
            'number.unique'=>'该编号已被使用！',
            'number.integer'=>'参数格式必须为整形！',
            'name.required'=>'姓名不能为空！',
            'category.required'=>'类别不能为空！',
            'category.integer'=>'参数格式必须为整形！'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'message'=>$errors[0],
            'code'=>'ERROR'
        ], 422);
    }
}
